services:
  tts-server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.dev
      args:
        BASE: nvidia/cuda:11.8.0-base-ubuntu22.04
    image: coqui-ai-tts-server:gpu
    gpus: all
    ports:
      - "5002:5002"
    environment:
      - DEVICE=cuda
      - COQUI_TOS_AGREED=1
      - PYTHONUNBUFFERED=1
    command: ["python3", "TTS/server/server.py", "--device", "cuda" ]
    stdin_open: false
    tty: false
